version: "3"

services:
    postgres:
        image: postgres:13
        # restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak_db
            POSTGRES_USER: keycloak_user
            POSTGRES_PASSWORD: keycloak_pass

    graphql-engine:
        image: hasura/graphql-engine:v2.0.9
        # restart: unless-stopped
        ports:
            - "9090:8080"
        depends_on:
            - "postgres"
        environment:
            ## postgres database to store Hasura metadata
            HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://keycloak_user:keycloak_pass@postgres:5432/keycloak_db
            ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
            PG_DATABASE_URL: postgres://keycloak_user:keycloak_pass@postgres:5432/keycloak_db
            ## enable the console served by server
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
            ## enable debugging mode. It is recommended to disable this in production
            HASURA_GRAPHQL_DEV_MODE: "true"
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            ## uncomment next line to set an admin secret
            # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

    # redis:
    #     image: "redis:6-alpine"
    #     restart: unless-stopped
    #     ports:
    #         - "6379:6379"
    #     networks:
    #         - reddit-clone

networks:
    reddit-clone:
        driver: bridge

volumes:
    mongo_data:
        driver: local
    postgres_data:
        driver: local
    # caddy-config:
    #     driver: local
